# jekyll setup
# ------------

source: ./_source
destination: ./_site
plugins: ./_plugins
permalink: /:categories/:title.html
markdown: redcarpet
pygments: true


# base page setup
# ---------------

url: http://www.roccogeorgi.com
title: Rocco Georgi
subtitle: Web Technology Consultant
author: Rocco Georgi


# ui defaults
# -----------

banner: duplotower.jpg


# plugin settings
# ---------------

asset_bundler:
    servenodev: true
    base_path: '/assets/'
    compress:
        js: yui
        css: yui
    markup_templates:
        js: '<script src="{{url}}"></script>'
        css: '<link rel="stylesheet" type="text/css" href="{{url}}">'
